Transfer shares
maticnetwork/contracts pull request #340
Opened 2020-12-28 13:42 UTC by imyourm8

2020-12-29 09:28 UTC, imyourm8 commented
I am not sure why tests are failing in CI, locally and in different PR they all passed.

2020-12-29 10:23 UTC, jdkanani commented on contracts/staking/validatorShare/ValidatorShare.sol
> +        super._transfer(from, to, value.add(restakedShares));
We chould just do 
```suggestion
        // get rewards for recipient 
        _withdrawAndTransferReward(to);
        // get rewards for sender 
        _withdrawAndTransferReward(from);
        // move shares to recipient
        super._transfer(from, to, value);
```

2020-12-29 10:24 UTC, jdkanani requested changes

2020-12-29 10:24 UTC, jdkanani commented on contracts/staking/validatorShare/ValidatorShare.sol
> +        (uint256 restakedShares, ) = _restake(from);
```suggestion
        if (to == 0x0 || from == 0x0) {
            // get rewards for recipient 
            _withdrawAndTransferReward(to);
            // convert rewards to shares
            (uint256 restakedShares, ) = _restake(from);
        }
```

2020-12-30 10:43 UTC, jdkanani commented on contracts/staking/validatorShare/ValidatorShare.sol
> +    function restake() public returns(uint256, uint256) {
Do we need this change?

2020-12-30 10:57 UTC, jdkanani approved these changes

2020-12-30 13:31 UTC, merged